---
#
# ios_route_maps.yml
#
# !
# route-map TODO-IPv4 permit 10
#  match ip address prefix-list PERMIT-ALL-IPv4
# !
# route-map NADA-IPv4 permit 10
#  match ipv6 address prefix-list DENY-ALL-IPv4
# !
# route-map TODO-IPv6 permit 10
#  match ipv6 address prefix-list PERMIT-ALL-IPv6
# !
# route-map NADA-IPv6 permit 10
#  match ipv6 address prefix-list DENY-ALL-IPv6
# !

  - name: Route Maps TODO-IPv4, NADA-IPv4, TODO-IPv6, NADA-IPv6
    cisco.ios.ios_route_maps:
      config:
        - route_map: TODO-IPv4 
          entries:
          - sequence: 10
            action: permit 
            match: 
              ip:
                address:
                  prefix_lists:
                    - PERMIT-ALL-IPv4 
        - route_map: NADA-IPv4 
          entries:
          - sequence: 10
            action: permit 
            match: 
              ip:
                address:
                  prefix_lists:
                    - DENY-ALL-IPv4 
        - route_map: TODO-IPv4-OUT 
          entries:
          - sequence: 10
            action: permit 
            match: 
              ip:
                address:
                  prefix_lists:
                    - PERMIT-ALL-IPv4 
        - route_map: TODO-IPv6 
          entries:
          - sequence: 10
            action: permit 
            match: 
              ipv6:
                address:
                  prefix_list: PERMIT-ALL-IPv6 
        - route_map: NADA-IPv6 
          entries:
          - sequence: 10
            action: permit 
            match: 
              ipv6:
                address:
                  prefix_list: DENY-ALL-IPv6 
        - route_map: TODO-IPv6-OUT
          entries:
          - sequence: 10
            action: permit 
            match: 
              ipv6:
                address:
                  prefix_list: PERMIT-ALL-IPv6
    tags: T3

# !
# route-map RPKI permit 10
#  match rpki valid
#  set local-preference 200
# !
# route-map RPKI permit 20
#  match rpki notfound
#  set local-preference 100

  - name: Route Maps RPKI
    cisco.ios.ios_route_maps:
      config:
        - route_map: RPKI 
          entries:
          - sequence: 10
            action: permit 
            match: 
              rpki:
                valid: yes
            set:
              local_preference: 200
    tags: T3

    # Differences!!!!: Cisco: not_found | FRR: notfound
  - name: Add match rpki notfound in Route Map AS-PATH
    cisco.ios.ios_config:
      lines:
      -  match rpki notfound 
      -  set local-preference 100
      parents: route-map RPKI permit 20 
      match: exact
    tags: T3


  - name: save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified
      backup: yes
      backup_options:
        filename: t3_config.{{ ansible_date_time.iso8601 }}
    tags: T3
