---
#
# ios_bgp_as_path.yml
#
# !
# bgp as-path access-list AS-PATH-PERMIT-LIST seq 5 permit ^65000(_65000)*$
# bgp as-path access-list AS-PATH-PERMIT-LIST seq 10 permit ^65000(_[0-9]+)*_(65001|65002|65003|65004)$
# bgp as-path access-list AS-PATH-PERMIT-LIST seq 15 permit ^65000(_[0-9]+)*_(65005)$
# !


  - name: IRR bgpq4
    shell: bgpq4 -h irr.lacnic.net -f {{ iborder_asn }}  -l AS-PATH-PERMIT-LIST {{ irr_as_set }}
    register: ip_as_path
    tags: T6

  - debug:
      msg: "{{ ip_as_path.stdout }}" 
    tags: T6

  - name: Create a directory if it does not exist
    file:
      path: ./template
      state: directory
      mode: '0755'
    tags: T6

  - name: Create Jinja Template
    local_action: copy content="{{ ip_as_path.stdout | regex_replace('ip', 'bgp', ignorecase=True) }}" dest="./template/bgp_as_path.j2"
    tags: T6

  - name: configurable backup path
    cisco.ios.ios_config:
      src: template/bgp_as_path.j2
    tags: T6

# !
# route-map PERMIT-SOME-ASN permit 10
#  match as-path AS-PATH-PERMIT-LIST
# !

  - name: Route Map AS-PATH
    cisco.ios.ios_config:
      lines:
      - match as-path AS-PATH-PERMIT-LIST
      parents: route-map PERMIT-SOME-ASN permit 10
      match: exact
    tags: T6

  - name: Save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified
      backup: yes
      backup_options:
        filename: t6_config.{{ ansible_date_time.iso8601 }}
    tags: T6
