---
#
# route_map_rpki_aspath.yml
#
# !
# route-map RPKI permit 10
#  match as-path AS-PATH-PERMIT-LIST
#  match rpki valid
#  set local-preference 200
# exit
# !
# route-map RPKI permit 20
#  match as-path AS-PATH-PERMIT-LIST
#  match rpki notfound
#  set local-preference 100
# exit
# !

  - name: T8 - Add match as-path and rpki valid in Route Map RPKI 
    cisco.ios.ios_config:
      lines:
      - match as-path AS-PATH-PERMIT-LIST
      - match rpki valid 
      - set local-preference 200
      parents: route-map RPKI permit 10 
      match: exact
    tags: T8

  - name: T8 - Add match as-path and rpki notfound in Route Map RPKI
    cisco.ios.ios_config:
      lines:
      - match as-path AS-PATH-PERMIT-LIST
      - match rpki notfound 
      - set local-preference 100
      parents: route-map RPKI permit 20 
      match: exact
    tags: T8

  - name: T8 - Save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified
      backup: yes
      backup_options:
        filename: t8_config.{{ ansible_date_time.iso8601 }}
    tags: T8
